apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cnet-gh-quay-tekton
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnet-gh-quay-tekton 
  name: cnet-gh-quay-tekton
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cnet-gh-quay-tekton 
